### ISSUE TITLE
InternalServerError: failed while resolving client request

### ISSUE THREAD

**Issue by crtr0** [lvauvillier/nexus-plugin-shield#4]
I am trying to use this plug-in, but a server error keeps getting thrown. I've reduced the usage to the simplest possible case and still can't get it to work:

**app.ts**

```
import cors from 'cors'
import { settings, server, use, schema } from 'nexus'
import { prisma } from 'nexus-plugin-prisma'
import { shield, rule, allow, deny, not, and, or } from 'nexus-plugin-shield'
import authenticated from './security'

// Prisma is our connection to the underlying database
use(prisma())

const permissions = shield({
  rules: {
    Query: {
      '*': allow,
    },
    options: {
      fallbackRule: allow,
    },
  },
})

use(permissions)

// Enables CORS for our GraphQL API server
server.express.use(cors())

// Authenticates requests using Auth0
server.express.use((req: any, res, next) => {
  authenticated(req, res, () => {
    const { user } = req
    schema.addToContext(() => {
      return { user }
    })
    next()
  })
})

settings.change({
  server: {
    playground: true,
  },
})
```

And the error I'm seeing is:

```
nexus:server:graphql InternalServerError: failed while resolving client request
    at /Users/crabasa/Code/fizbuz-api/node_modules/nexus/dist/runtime/server/handler-graphql.js:50:64
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/crabasa/Code/fizbuz-api/node_modules/nexus/dist/runtime/server/server.js:97:9
```

**Comment by crtr0** [comment]
Update: turned-out the plug-in wasn't playing nicely with some custom middleware I had written. Having middleware sprinkled all over your app turns out to be hard to debug. Closing this issue.
